config/routes.rb
Rails.application.routes.draw do

  root to: 'splash#home'

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index]

      get '/most_popular', to: 'items#most_popular'
    end
  end

  resources 'items', only: [:index, :show]
  post '/retired_item', to: 'items#reject', as: 'retired_item'

  resources :orders, only: [:index, :show, :create, :update]

  resources :carts, only: [:create]
  put    '/carts', to: 'carts#update'
  delete '/carts', to: 'carts#destroy'
  get    '/cart', to: 'carts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update] 
  
  get '/dashboard', to: 'users#show'

  namespace :admin do 
    get '/dashboard', to: 'base#dashboard'
    resources :items, only: [:index, :edit, :update]
  end

  get '/:category_name', to: 'categories#show', as: 'category'
end

app/views/admin/_admin-orders.html.haml
.orders-container
  .orders-header
    .header
      %h3 #{@header if @header} Orders
    .sort-by
      .dropdown
        %a.dropdown-toggle{ "data-toggle" => "dropdown", href: "#" }
          Filter by Status
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to 'all', admin_dashboard_path
          - @statuses.each do |status|
            %li
              = link_to status, admin_dashboard_path(:status => status)
  - @orders.each do |order|
    .order
      .order-info
        %p <strong>User: </strong> #{order.user.name}
        %p <strong>Total:</strong> #{number_to_currency(order.total_price)} 
        %p <strong>Submitted:</strong> #{order.created_at}
        - if order.completed? || order.cancelled?
          %p <strong>Status:</strong> #{order.status}
        - else
          .dropdown
            %a.dropdown-toggle{ "data-toggle" => "dropdown", href: "#" }
              <strong>Status:</strong> #{order.status}
              %b.caret
            %ul.dropdown-menu
              - if order.ordered?
                %li
                  = link_to('mark as paid', order_path(order, status: 1), method: :put)
              - if order.paid?
                %li
                  = link_to('mark as completed', order_path(order, status: 3), method: :put)
              - if order.paid? || order.ordered?
                %li
                  = link_to('cancel', order_path(order, status: 2), method: :put)
        %p <strong>Updated At:</strong> #{order.updated_at}
        %p <strong>Order ID:</strong> #{order.id}
      .order-button
        = link_to 'Order Details', order_path(order), class: 'btn'

app/views/admin/admin_items.html.haml
%h1 View All Items
%hr 
%section.admin-items-table
  %table
    %th Item Picture
    %th Item Info
    - @items.each do |item|
      %td
        %img{'src' => item.image_url, 'alt' => item.name}
      %td
        %ul
          %li= link_to item.name
          %li= item.description
          %li= item.status
          %li= button_to "Edit", edit_admin_items_path(item)
%hr

app/views/admin/dashboard.html.haml
%section.users-dashboard
  %h2 Admin Dashboard
  = render partial: 'shared/user_info'

%hr
= link_to "View All Items", admin_items_path, class: "dashboard-button"

= render partial: 'admin/admin-orders' 