config/routes.rb
Rails.application.routes.draw do

  root to: 'splash#home'

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index]

      get '/most_popular', to: 'items#most_popular'
    end
  end

  resources 'items', only: [:index, :show]
  post '/retired_item', to: 'items#reject', as: 'retired_item'

  resources :orders, only: [:index, :show, :create, :update]

  resources :carts, only: [:create]
  put    '/carts', to: 'carts#update'
  delete '/carts', to: 'carts#destroy'
  get    '/cart', to: 'carts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update] 
  
  get '/dashboard', to: 'users#show'

  namespace :admin do 
    get '/dashboard', to: 'base#dashboard'
    resources :items, only: [:index, :edit, :update]
  end

  get '/:category_name', to: 'categories#show', as: 'category'
end

app/views/shared/_flash.html.haml
%article
  - flash.each do |key, value|
    = content_tag :div, sanitize(value), class: "alert alert-#{key}"

app/views/shared/_items.html.haml
- items.each do |item|
  - if item.active?
    %section.item-card{ :id => item.name.tr(' ', '-') }
      %article.item-card-image
        %a{'href' => item_path(item)}
          %img{ 'src' => item.image_url, 'alt' => item.name }
      %article.item-info
        %aside.item-title
          %h3
            = link_to item.name, item_path(item)
        %aside.item-price
          = format_price_per_unit(item)
      %article.item-description
        %p
          = item.description
      %article.item-card-button
        = button_to "Add to Cart", carts_path(item_id: item.id)

app/views/shared/_items_index.html.haml
%article.search
  = render partial: 'shared/search_form' if @q

- if active_search?
  %article.category-header
    %h2
      = "Results for \"#{@q.conditions.first.values.first.value}\""
  %article.items-container
    - if @items.any?
      = render partial: 'shared/items', locals: { items: @items }

    - else
      %h3 Sorry, no results found.

- else
  - @categories.each do |category|
    %article.category-header
      %h1
        = category.title
    %article.items-container
      = render partial: 'shared/items', locals: { items: category.items }

app/views/shared/_nav.html.haml
%nav.navbar.navbar-inverse{ role: "navigation" }
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{ "data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button" }
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{ href: root_path } 
      %img{ "src" => "/scoopful-logo.svg", "alt" => "logo" }
  / Collect the nav links, forms, and other content for toggling
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav.navbar-left
      %li 
        - if current_user
          = link_to "Logged in as #{current_user.first_name}", dashboard_path
    %ul.nav.navbar-nav.navbar-right
      %li
        %a{ href: cart_path }
          View Cart
          %span.badge= @cart.total_count
      %li
        - if current_user
          = link_to 'Logout', logout_path, method: :delete
        -else
          = link_to 'Login', login_path
      %li.dropdown
        %a.dropdown-toggle{ "data-toggle" => "dropdown", href: "#" }
          Categories
          %b.caret
        %ul.dropdown-menu
          - categories.each do |category|
            %li
              %a{ href: category_path(category) }
                = category.title
          %li
            %a{ href: items_path }
              All Categories
  / /.navbar-collapse

app/views/shared/_search_form.html.haml
= search_form_for @q do |f|
  = f.label 'Looking for something?'
  = f.search_field :name_or_description_or_category_title_cont
  = f.submit

app/views/shared/_user_info.html.haml
%section.users-welcome
  %article.user-name
    %strong= "Name: #{current_user.name}"
  %article.user-email
    %strong= "Email: #{current_user.email}"
  %article
    = link_to('Update Profile Information', edit_user_path(current_user))