config/routes.rb
Rails.application.routes.draw do

  root to: 'splash#home'

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index]

      get '/most_popular', to: 'items#most_popular'
    end
  end

  resources 'items', only: [:index, :show]
  post '/retired_item', to: 'items#reject', as: 'retired_item'

  resources :orders, only: [:index, :show, :create, :update]

  resources :carts, only: [:create]
  put    '/carts', to: 'carts#update'
  delete '/carts', to: 'carts#destroy'
  get    '/cart', to: 'carts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update] 
  
  get '/dashboard', to: 'users#show'

  namespace :admin do 
    get '/dashboard', to: 'base#dashboard'
    resources :items, only: [:index, :edit, :update]
  end

  get '/:category_name', to: 'categories#show', as: 'category'
end

app/models/order.rb
class Order < ApplicationRecord  
  belongs_to :user
  has_many :orders_items
  has_many :items, through: :orders_items

  enum status: %w(ordered paid cancelled completed)

  def total_price
    orders_items.map { |item| item.current_price_per_unit * item.quantity.to_f }.sum
  end

  def subtotal(item)
    order_item(item).subtotal
  end

  def order_item(item)
    orders_items.find_by(item_id: item.id)
  end

  def order_item_quantity(item)
    order_item(item).quantity
  end

  def self.by_status(status)
    orders = Order.send(status) rescue Order.all
    orders.order('updated_at DESC')
  end

  def verified_user?(current_user)
    user_id == current_user.id || current_user.admin?
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :require_admin, only: [:update]

  def index
    @orders     = current_user.sorted_orders
    @head_title = ' | Orders'
  end

  def show
    @order      = Order.find(params[:id])
    @head_title = " | #{@order.id}"

    redirect_to dashboard_path unless @order.verified_user?(current_user)
  end

  def create
    order = current_user.orders.create
    Checkout.new(@cart.contents).submit(order)

    session.delete(:cart) 
    flash[:success] = "Order was successfully placed"
    redirect_to orders_path
  end

  def update
    order = Order.find(params[:id])
    order.update(status: params[:status].to_i)

    flash[:success] = "Order #{order.id} updated to #{order.status}"
    redirect_to admin_dashboard_path
  end
end

app/views/orders/index.html.haml
.orders-container
  %h3 Your Orders
  - @orders.each do |order|
    .order
      .order-info
        %p <strong>Total:</strong> #{number_to_currency(order.total_price)} 
        %p <strong>Submitted:</strong> #{order.created_at}
        %p <strong>Status:</strong> #{order.status}, #{order.updated_at}
        %p <strong>Order ID:</strong> #{order.id}
      .order-button
        = link_to 'Order Details', order_path(order), class: 'btn'

app/views/orders/show.html.haml
.order-container
  .order-header
    .order-price
      %h3 <strong>Total:</strong> #{number_to_currency(@order.total_price)}
    .order-info
      - if current_admin?
        %p <strong>User:</strong> #{@order.user.name}
        %p <strong>Email:</strong> #{@order.user.email}
      %p <strong>Submitted:</strong> #{@order.created_at}
      %p <strong>Status:</strong> #{@order.status}, Date: #{@order.updated_at}
      %p <strong>Order ID:</strong> #{@order.id}

  %ul.order-list
    - @order.items.each do |item|
      %li.order-item
        .img-container
          %img{ :src => "#{ item.image_url }", :alt => "item.name", :class => "img-responsive" }
        %section.info
          %h2= link_to item.name, item_path(item)
          %p= item.description
          %p= format_price_per_unit(@order.order_item(item))
          %p= "Quantity: #{@order.order_item_quantity(item)}"
          %p= "Subtotal: #{number_to_currency(@order.subtotal(item))}"
      %hr

  .orders-link
    = link_to 'Back to Orders', orders_path