config/routes.rb
Rails.application.routes.draw do

  root to: 'splash#home'

  namespace :api do
    namespace :v1 do
      resources :items, only: [:index]

      get '/most_popular', to: 'items#most_popular'
    end
  end

  resources 'items', only: [:index, :show]
  post '/retired_item', to: 'items#reject', as: 'retired_item'

  resources :orders, only: [:index, :show, :create, :update]

  resources :carts, only: [:create]
  put    '/carts', to: 'carts#update'
  delete '/carts', to: 'carts#destroy'
  get    '/cart', to: 'carts#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create, :edit, :update] 
  
  get '/dashboard', to: 'users#show'

  namespace :admin do 
    get '/dashboard', to: 'base#dashboard'
    resources :items, only: [:index, :edit, :update]
  end

  get '/:category_name', to: 'categories#show', as: 'category'
end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(session_cart)
    @contents = session_cart || {}
  end

  def add_item(item_id, quantity = 1)
    contents[item_id.to_s] ||= 0
    contents[item_id.to_s]  += (1 * quantity)
  end

  def total_count
    contents.values.sum
  end

  def count_of(item_id)
    contents[item_id.to_s]
  end

  def items
    item_ids = contents.keys
    Item.where(id: item_ids)
  end

  def total_price
    items.map { |item| item.price_per_unit * contents[item.id.to_s] }.sum.round(2)
  end

  def remove(item_id)
    @contents.delete(item_id.to_s)
  end

  def subtotal_of(item_id)
    (Item.find(item_id).price_per_unit * contents[item_id.to_s]).round(2)
  end

  def update_item(cart_params)
    id       = cart_params['item_id']
    quantity = cart_params['quantity'].to_i

    process_item_quantity(id, quantity)
  end

  def process_item_quantity(id, quantity)
    return remove(id) if quantity <= 0
    contents[id.to_s] = quantity
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include ActionView::Helpers::TextHelper

  skip_before_action :require_login

  def create
    item = Item.find(params[:item_id])

    @cart.add_item(item.id)
    session[:cart] = @cart.contents

    flash[:success] = "You now have 
    #{pluralize(@cart.count_of(item.id), "pound")} of 
    #{item.name} in your #{view_context.link_to "cart", cart_path}."
    
    redirect_back(fallback_location: items_path)
  end

  def index
    @head_title = ' | Your Cart'
    @items      = @cart.items
  end

  def update
    @cart.update_item(params)
    session[:cart] = @cart.contents

    redirect_to cart_path
  end

  def destroy
    item = Item.find(params[:item_id])
    @cart.remove(item.id)

    flash[:success] = "Successfully removed
    #{view_context.link_to(item.name, item_path(item))}
    from your cart."

    redirect_to cart_path
  end

end

app/views/carts/index.html.haml
.cart-container
  .cart-header
    %h3 Items in Cart:
    .checkout-link
      - if current_user
        = link_to('Check out Cart', orders_path, :method => :post)
      - else
        = link_to('Log in or Register to Check out', login_path)

  %ul.cart-list
    - @items.each do |item|
      %li.cart-item
        .img-container
          %img{ :src => "#{ item.image_url }", :alt => "item.name", :class => "img-responsive" }
        %section.info
          %h2= item.name
          %p= item.description
          %p= format_price_per_unit(item)
          %p= label_tag :quantity, 'Quantity:'
          = form_tag :carts, method: :put do
            = hidden_field_tag :item_id, item.id
            = number_field_tag :quantity, @cart.count_of(item.id)
            = submit_tag "Update"
          %p= "Subtotal: #{number_to_currency(@cart.subtotal_of(item.id))}"
          = button_to "Remove", carts_path(item_id: item.id), method: :delete
      %hr
  %section.cart-total
    %h3= "Total Price: #{number_to_currency(@cart.total_price)}"